# Generated by Django 2.2.4 on 2021-08-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0006_auto_20210808_1327'),
        ('estudante', '0003_duvidaaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvidaaula',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptor_mensagem', to='professor.Video'),
        ),
    ]
