# Generated by Django 2.2.4 on 2021-08-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0004_duvidaaula_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duvidaaula',
            name='receptor',
        ),
        migrations.AlterField(
            model_name='duvidaaula',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aula_mensagem', to='professor.Video'),
        ),
        migrations.AlterField(
            model_name='duvidaaula',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
