# Generated by Django 2.2.4 on 2021-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0005_auto_20210822_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvidaaula',
            name='mensagem',
            field=models.CharField(max_length=10000000),
        ),
    ]
