# Generated by Django 2.2.4 on 2021-09-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0008_auto_20210823_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvidaaula',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
