# Generated by Django 2.2.4 on 2021-10-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoInterna', '0002_auto_20211002_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamagazine',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
