# Generated by Django 2.2.4 on 2021-08-01 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(blank=True, max_length=300, null=True)),
                ('tipoDocumento', models.CharField(blank=True, choices=[('Bilhete de identidade', 'Bilhete de identidade'), ('Passaporte', 'Passaporte'), ('Carta de condução', 'Carta de condução'), ('Atestado de residência', 'Atestado de residência')], max_length=60, null=True)),
                ('numeroDocumento', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Prefiro não informar', 'Prefiro não informar')], default='Masculino', max_length=25, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('telefone2', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('emailAlternativo', models.EmailField(blank=True, max_length=200, null=True)),
                ('morada', models.CharField(blank=True, max_length=300, null=True)),
                ('fotoPerfil', models.ImageField(blank=True, default='user.png', null=True, upload_to='')),
                ('dataRegisto', models.DateTimeField(auto_now_add=True)),
                ('breveDescricao', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
