# Generated by Django 2.2.4 on 2021-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20210808_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
