# Generated by Django 2.2.4 on 2021-09-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_auto_20210911_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tituloVideo',
            field=models.CharField(max_length=100),
        ),
    ]
