# Generated by Django 2.2.4 on 2021-10-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0008_auto_20210911_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacaoTurma', models.CharField(max_length=100)),
                ('breveDescricao', models.TextField()),
                ('dataRegisto', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.Curso')),
            ],
        ),
    ]
