# Generated by Django 2.2.4 on 2021-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0011_curriculoprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculoprofessor',
            name='localActuacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
